categories:
  - id: main
    name: Main Executable
    paths:
      - Game
  - id: hunter
    name: Human Hunter
    paths:
      - Overlays/hunter
  - id: skinner
    name: Melchiahim
    paths:
      - Overlays/skinner
  - id: wallcr
    name: Zephonim
    paths:
      - Overlays/wallcr

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - LIBS
  - header

output: ./objdiff.json