categories:
  - id: main
    name: Main Executable
    paths:
      - Game
  - id: hunter
    name: Human Hunter Overlay
    paths:
      - Overlays/hunter
  - id: skinner
    name: Melchiahim Overlay
    paths:
      - Overlays/skinner
  - id: wallcr
    name: Zephonim Overlay
    paths:
      - Overlays/wallcr
  - id: aluka
    name: Rahabim Overlay
    paths:
      - Overlays/aluka
  - id: skinbos
    name: Melchiah Overlay
    paths:
      - Overlays/skinbos

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - LIBS
  - header

output: ./objdiff.json